<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\NewFolder1\**" />
    <Compile Remove="wwwroot\NewFolder\**" />
    <Content Remove="wwwroot\NewFolder1\**" />
    <Content Remove="wwwroot\NewFolder\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder1\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder\**" />
    <None Remove="wwwroot\NewFolder1\**" />
    <None Remove="wwwroot\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Components\Pages\CoursesRegistertion}.razor" />
    <Content Remove="Data\documentos_db.json" />
    <Content Remove="Data\Documents.razor" />
    <Content Remove="wwwroot\app.css" />
    <Content Remove="wwwroot\upload.cs" />
    <Content Remove="wwwroot\uploads.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\index.css" />
    <None Include="wwwroot\Diseño sin título %2813%29.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\css\dashboardIndex.css">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\css\register.css">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

</Project>
